version: "3.8"

services:
    bitcoind:
        image: ruimarinho/bitcoin-core:0.21-alpine
        command:
            -printtoconsole
            -rpcuser=clightning4j
            -rpcpassword=clightning4j
            -server
            -listen
            -prune=550
        ports:
        - 8332:8332

    lightningd:
        image: vincenzopalazzo/clightning4j-node:v0.10.0-dev1
        depends_on: 
            - bitcoind
        volumes:
            - ./data:/home/clightning4j
        ports: 
            - 7000:7000
        command:
            --network=bitcoin 
            --alias=clihgnting4j-node 
            --disable-plugin=bcli
            --bitcoin-rpcuser=clightning4j 
            --bitcoin-rpcpassword=clightning4j
            --bitcoin-rpcurl=http://bitcoind_default:8332 
            --btcli4j-pruned
            --log-level=debug
            --jrest-port=7000