version: "3.8"

services:
    lightningd:
        image: vincenzopalazzo/clightning4j-node:v0.10.0-dev1
        volumes:
            - ./data:/home/clightning4j
        ports: 
            - 7000:7000
        command:
            --network=bitcoin 
            --alias=clihgnting4j-node 
            --disable-plugin=bcli
            --log-level=debug
            --jrest-port=7000