version: "3.8"

services:
    ngnix:
        image: nginx:latest
        depends_on: 
            - lightningd
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:8080"
        restart: on-failure
    lnchecker:
        image: vincenzopalazzo/ln-dashboard:v0.0.2
        restart: on-failure
        environment:
            - NEXT_PUBLIC_REST_URL=http://ngnix:8080/rest
    lightningd:
        image: vincenzopalazzo/clightning4j-node:v0.10.2
        build: .
        depends_on:
            - lnchecker
        volumes:
            - ./data:/home/clightning4j
        command:
            --network=testnet
            --alias=clihgnting4j-node
            --rgb=f07178
            --disable-plugin=bcli
            --log-level=debug
            --jrest-port=7001
            --jrest-on-startup
            --bind-addr=127.0.0.1:9735
            --proxy=127.0.0.1:9050
            --addr=statictor:127.0.0.1:9051
            --log-file=/home/clightning4j/.lightning/log.log