version: "3.8"

services:
    bitcoind:
        image: ruimarinho/bitcoin-core:0.21-alpine
        command:
            -printtoconsole
            -rpcuser=clightning4j
            -rpcpassword=clightning4j
            -server
            -listen
            -testnet
            -prune=550
        ports:
        - 8332:8332

    lightningd:
        image: vincenzopalazzo/clightning4j-node:v0.12.0-rc1-hotfix.1
        depends_on:
            - bitcoind
        volumes:
            - ./data:/home/clightning4j
        ports:
            - 7000:7000
        command:
            --network=testnet
            --alias=clighting4j-node
            --disable-plugin=bcli
            --bitcoin-rpcuser=clightning4j
            --bitcoin-rpcpassword=clightning4j
            --bitcoin-rpcurl=http://bitcoind_default:8332
            --btcli4j-pruned
            --lnmetrics-urls=https://api.lnmetrics.info/query
            --log-level=debug